---
irc:
  server:
  port: 6667
  user: TopicBot
  nick: TopicBot
  name: A Topic Sync Bot
  # IRC channel to join (e.g. '#TopicBotTest')
  channel: 
  # Optional - Usermodes to set upon IRC join
  usermode: +ix
  # Optional - Bot name and command to auth with IRC services
  # example: 
  # bot: Q@CServe.quakenet.org
  # cmd: AUTH TopicBot password
  auth:
    bot:
    cmd:
discord:
  token:
  # The ID of the channel to track, found using discord dev-mode 
  # and right-clicking on the channel
  channelID:
# Optional - Discord topic update message format.
# Omit updateFormat and emojis to disable this feature.
# [Emoji] Topic Updated: [The topic message]
updateFormat: "%s Topic Updated: %s"
# Optional - Random Emojis for added topic update message flair
emojis:
  - ⚠️
  - 🔔
  - 🚨
...